spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.psrzcvqxersquhfnnjtn
spring.datasource.password=DASIG123RIIS
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.data-source-properties.prepareThreshold=0

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET:PLEASE_SET_JWT_SECRET}
app.security.jwt.access-token-ttl-seconds=3600

app.s3.bucket=dasig-research-files
app.s3.region=ap-northeast-1
app.s3.endpoint=https://psrzcvqxersquhfnnjtn.storage.supabase.co/storage/v1/s3
app.s3.access-key=your-access-key
app.s3.secret-key=your-secret-key

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB