spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.psrzcvqxersquhfnnjtn
spring.datasource.password=DASIG123RIIS
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.data-source-properties.prepareThreshold=0

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET:PLEASE_SET_JWT_SECRET}

app.s3.bucket=dasig-research-files
app.s3.region=ap-southeast-1
app.s3.endpoint=https://psrzcvqxersquhfnnjtn.supabase.co/storage/v1/s3
app.s3.access-key=${SUPABASE_S3_ACCESS_KEY:}
app.s3.secret-key=${SUPABASE_S3_SECRET_KEY:}
