spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.psrzcvqxersquhfnnjtn
spring.datasource.password=DASIG123RIIS
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.data-source-properties.prepareThreshold=0

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET:PLEASE_SET_JWT_SECRET}
app.security.jwt.access-token-ttl-seconds=3600

app.s3.bucket=dasig-research-files
app.s3.region=ap-northeast-1
app.s3.endpoint=https://psrzcvqxersquhfnnjtn.storage.supabase.co/storage/v1/s3
app.s3.access-key=610e38205054e834b5836080ba22290b
app.s3.secret-key=d04687241419a613ef635a1060adaf06edcd2ba3788a7f43c4ef0ed8aa8eddc1

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

ai.service.url=http://localhost:8000

spring.mail.host=smtp.sendgrid.net
spring.mail.port=587
spring.mail.username=apikey
spring.mail.password=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
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
app.notification.admin-email=dasig.dost7@gmail.com
spring.mail.from=dasig.dost7@gmail.com